In [1]:
import torch

In [2]:
import torchvision

In [3]:
print(torch.backends.mps.is_available())

True


In [4]:
#This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [5]:
#This is a 2-D Tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [6]:
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [7]:
#Get the height/number of rows of b
print(b.shape[0])

4


In [8]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do 
#c = torch.tensor([2,2,1], dtype = torch.float)

In [9]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#d = torch.tensor([2,2,1], dtype = torch.double)

In [10]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [11]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [12]:
print(c.mean())

tensor(2.5833)


In [13]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [14]:
print(c.std())

tensor(1.5050)


In [15]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [16]:
#Reshape b
#Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))
#Assign b a new shape 
b = b.view(1, -1)
print(b)
print(b.shape)
#We can even reshape 3D tensors
print('\n')
#Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channels, rows, columns)
three_dim = torch.randn(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12)) # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])




tensor([[[ 0.6045, -1.1254,  0.1717, -0.7774],
         [ 0.9981, -0.5069,  0.8055, -0.2212],
         [ 0.5582,  0.9529,  0.2080,  0.0229]],

        [[-0.3966,  0.5143,  0.5083, -0.9010],
         [-1.7610, -0.0419,  0.9386, -0.3832],
         [ 0.8507,  0.6796,  1.2266,  1.2346]]])
tensor([[ 0.6045, -1.1254,  0.1717, -0.7774,  0.9981, -0.5069,  0.8055, -0.2212,
          0.5582,  0.9529,  0.2080,  0.0229],
        [-0.3966,  0.5143,  0.5083, -0.9010, -1.7610, -0.0419,  0.9386, -0.3832,
          0.8507,  0.6796,  1.2266,  1.2346]])
tensor([[ 0.6045, -1.1254,  0.1717, -0.7774,  0.9981

In [17]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[9.8031e-01, 4.6301e-01, 4.0783e-01, 2.7017e-01],
        [8.8663e-01, 2.5899e-01, 6.9302e-01, 1.8951e-01],
        [9.2206e-01, 2.6693e-01, 6.0785e-04, 2.7876e-03],
        [4.3980e-01, 8.1293e-01, 3.9340e-02, 7.9185e-01]])


In [18]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 an variance 1
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[-2.0357e+00,  5.3471e-01,  7.0637e-01, -2.1918e-01],
        [ 6.2338e-01,  5.9502e-02,  2.9052e+00, -6.1053e-02],
        [-3.4335e-01, -6.5391e-01, -1.9541e+00,  1.0605e+00],
        [ 5.9901e-01,  1.6549e+00, -1.8438e+00,  1.1528e-03]])
torch.float32


In [19]:
#Create an array of 5 random integers from values between 6 and 9 (exclusive of 10)
in_array = torch.randint(6, 10, (5,))
print(in_array)


tensor([7, 6, 7, 6, 8])


In [20]:
#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exclusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print(in_array2)

tensor([[7, 7, 9],
        [8, 6, 7],
        [7, 8, 8]])


In [21]:
#Get the number of elements in in_array
print(torch.numel(in_array))
#Get the number of elements in in_array
print(torch.numel(in_array2))

5
9


In [22]:
#Construct a 3x3 matrix of zeros and of dtype Long:
z = torch.zeros(3,3, dtype=torch.long)
print(z)
#Construct a 3x3 matrix of ones
o = torch.ones(3,3)
print(o)
print(o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [23]:
r2_like = torch.randn_like(r2, dtype=torch.double) #Convert the data type of the tensor
print(r2_like)

tensor([[-0.2265, -1.5132,  0.0417,  0.1152],
        [ 0.7888,  0.1318,  0.4233,  0.5100],
        [ 0.8274, -0.6805,  1.6070, -1.4346],
        [ 1.1246, -0.4356,  0.2052, -1.2746]], dtype=torch.float64)


In [24]:
#Add two tensors, make sure they are the same size and data type
add_result = torch.add(r, r2)
print(add_result)

tensor([[-1.0554,  0.9977,  1.1142,  0.0510],
        [ 1.5100,  0.3185,  3.5982,  0.1285],
        [ 0.5787, -0.3870, -1.9535,  1.0633],
        [ 1.0388,  2.4679, -1.8045,  0.7930]])


In [25]:
#In-place addition (change the value of r2)
r2.add_(r)
print(r2)

tensor([[-1.0554,  0.9977,  1.1142,  0.0510],
        [ 1.5100,  0.3185,  3.5982,  0.1285],
        [ 0.5787, -0.3870, -1.9535,  1.0633],
        [ 1.0388,  2.4679, -1.8045,  0.7930]])


In [26]:
print(r2[:,1])
print(r2[:,:2])
print(r2[:3,:])
num_ten = r2[2,3]
print(num_ten)
print(num_ten.item())
print(r2[2,:])

tensor([ 0.9977,  0.3185, -0.3870,  2.4679])
tensor([[-1.0554,  0.9977],
        [ 1.5100,  0.3185],
        [ 0.5787, -0.3870],
        [ 1.0388,  2.4679]])
tensor([[-1.0554,  0.9977,  1.1142,  0.0510],
        [ 1.5100,  0.3185,  3.5982,  0.1285],
        [ 0.5787, -0.3870, -1.9535,  1.0633]])
tensor(1.0633)
1.063307285308838
tensor([ 0.5787, -0.3870, -1.9535,  1.0633])
