In [2]:
import torch

In [3]:
import torchvision

In [8]:
print(torch.backends.mps.is_available())

True


In [9]:
#This is a 1-D Tensor
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [11]:
#This is a 2-D Tensor
b = torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[2, 1, 4],
        [3, 5, 4],
        [1, 2, 0],
        [4, 3, 2]])


In [12]:
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [13]:
#Get the height/number of rows of b
print(b.shape[0])

4


In [14]:
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do 
#c = torch.tensor([2,2,1], dtype = torch.float)

In [15]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#d = torch.tensor([2,2,1], dtype = torch.double)

In [16]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [17]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [18]:
print(c.mean())

tensor(2.5833)


In [19]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [20]:
print(c.std())

tensor(1.5050)


In [21]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [31]:
#Reshape b
#Note: If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))
#Assign b a new shape 
b = b.view(1, -1)
print(b)
print(b.shape)
#We can even reshape 3D tensors
print('\n')
#Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channels, rows, columns)
three_dim = torch.randn(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12)) # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))

tensor([[2],
        [1],
        [4],
        [3],
        [5],
        [4],
        [1],
        [2],
        [0],
        [4],
        [3],
        [2]])
tensor([2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3],
        [5, 4, 1, 2],
        [0, 4, 3, 2]])
tensor([[2, 1, 4, 3, 5, 4, 1, 2, 0, 4, 3, 2]])
torch.Size([1, 12])




tensor([[[-0.3706,  1.3355,  2.3714, -1.6128],
         [ 0.3829, -0.1959, -0.0728,  0.3336],
         [-0.2476, -0.6222, -0.5815,  0.5566]],

        [[-2.1391, -0.2175,  0.3556,  1.0056],
         [ 1.7144, -1.6363,  0.2300, -0.5206],
         [-0.3519, -0.4391, -0.9755,  0.8017]]])
tensor([[-0.3706,  1.3355,  2.3714, -1.6128,  0.3829, -0.1959, -0.0728,  0.3336,
         -0.2476, -0.6222, -0.5815,  0.5566],
        [-2.1391, -0.2175,  0.3556,  1.0056,  1.7144, -1.6363,  0.2300, -0.5206,
         -0.3519, -0.4391, -0.9755,  0.8017]])
tensor([[-0.3706,  1.3355,  2.3714, -1.6128,  0.3829

In [32]:
#Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.3847, 0.6814, 0.5276, 0.0271],
        [0.0862, 0.5641, 0.6504, 0.0842],
        [0.4266, 0.0352, 0.8908, 0.9583],
        [0.2472, 0.7920, 0.9204, 0.9664]])


In [33]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 an variance 1
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[-0.1613,  1.6046, -1.0796, -1.5409],
        [ 1.4223,  2.1352, -1.5626, -0.1982],
        [ 0.2299, -0.5924, -0.4289, -0.4157],
        [ 0.4205,  0.4536, -0.7440, -1.8913]])
torch.float32


In [38]:
#Create an array of 5 random integers from values between 6 and 9 (exclusive of 10)
in_array = torch.randint(6, 10, (5,))
print(in_array)


tensor([6, 9, 8, 8, 8])


In [39]:
#Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exclusive of 10)
in_array2 = torch.randint(6,10, (3,3))
print(in_array2)

tensor([[9, 9, 6],
        [6, 9, 6],
        [7, 8, 6]])


In [42]:
#Get the number of elements in in_array
print(torch.numel(in_array))
#Get the number of elements in in_array
print(torch.numel(in_array2))

5
9


In [43]:
#Construct a 3x3 matrix of zeros and of dtype Long:
z = torch.zeros(3,3, dtype=torch.long)
print(z)
#Construct a 3x3 matrix of ones
o = torch.ones(3,3)
print(o)
print(o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [46]:
r2_like = torch.randn_like(r2, dtype=torch.double) #Convert the data type of the tensor
print(r2_like)

tensor([[-1.2096e+00, -4.6493e-01,  1.8210e+00,  2.8016e-01],
        [-3.3701e-02, -1.4938e+00,  5.9721e-01,  3.9938e-01],
        [-2.8173e-01,  3.7011e-01,  1.0719e+00, -6.1796e-01],
        [ 1.3610e+00, -1.3716e-02,  1.8620e-01,  5.8745e-04]],
       dtype=torch.float64)


In [47]:
#Add two tensors, make sure they are the same size and data type
add_result= torch.add(r, r2)
print(add_result)

tensor([[ 0.2235,  2.2861, -0.5520, -1.5138],
        [ 1.5086,  2.6993, -0.9122, -0.1139],
        [ 0.6565, -0.5572,  0.4620,  0.5427],
        [ 0.6678,  1.2457,  0.1764, -0.9249]])


In [48]:
#In-place addition (change the value of r2)
r2.add_(r)
print(r2)

tensor([[ 0.2235,  2.2861, -0.5520, -1.5138],
        [ 1.5086,  2.6993, -0.9122, -0.1139],
        [ 0.6565, -0.5572,  0.4620,  0.5427],
        [ 0.6678,  1.2457,  0.1764, -0.9249]])
